Change dummy Postgres health check to string
Avoid failure with podman-compose due to main file having it defined
as a string:

```
ValueError: can't merge value of test of type <class 'str'> and <class 'list'>
```

Signed-off-by: Georg Pfuetzenreuter <georg.pfuetzenreuter@suse.com>